name: "Sub-split Publishing"
# See Documentation/Developer/MonoRepository.rst for details
# on Sub-tree splitting

on: # yamllint disable-line rule:truthy
  create:
    tags:
      - "*.*.*"
  delete:
    tags:
      - "*.*.*"
  push:
    paths:
      - "packages/**/*"
    branches:
      - "main"

jobs:
  publish_sub_splits:
    runs-on: "ubuntu-latest"
    name: "Publish Sub-split"
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
        with:
          fetch-depth: "0"
          persist-credentials: "false"
      - uses: "frankdejonge/use-github-token@15e6289d07c12b3b1603268a628bb74f2e9765f4" # 1.1.0
        with:
          authentication: "typo3-documentation-team:${{ secrets.BOT_TOKEN }}"
          user_name: "TYPO3 Documentation Team"
          user_email: "documentation-automation@typo3.com"
      - name: "Cache splitsh-lite"
        id: "splitsh-cache"
        uses: "actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306" # v5.0.3
        with:
          path: "./.splitsh"
          key: "${{ runner.os }}-splitsh-d-101"
      - uses: "frankdejonge/use-subsplit-publish@0001015147267203898034927e8cccad3a7a9aa7" # 1.1.0
        with:
          source-branch: "main"
          config-path: "./config.subsplit-publish.json"
          splitsh-path: "./.splitsh/splitsh-lite"
          splitsh-version: "v1.0.1"
